In [1]:
import numpy as np

In [2]:
list_ =['1','2','3','4','5']

In [3]:
array_list = np.array(object=list_)

#QNO.1 ANS

In [5]:
list_

['1', '2', '3', '4', '5']

In [6]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

#Yes, there is a difference in the data type of variables list_ and array_list.

The list_ variable is a Python list object, which can hold elements of different data types. In this case, it holds string objects.

The array_list variable is a NumPy array object, which can hold elements of a single data type. In this case, it holds string objects as well, but they are stored as a homogeneous array of strings

In [10]:
print(type(list_))

<class 'list'>


In [11]:
print(type(array_list))

<class 'numpy.ndarray'>


#QNO.2 ANS

In [18]:
import numpy as np
list =['1','2','3','4','5']
array_list = np.array(object = list_)

for element in list_:
    print(type(element))
    
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


#QNO.3 ANS

In [19]:
list_ =['1','2','3','4','5']

In [20]:
array_list = np.array(object = list_, dtype =int)

In [21]:
list_

['1', '2', '3', '4', '5']

In [22]:
array_list

array([1, 2, 3, 4, 5])

In [23]:
print(type(list_))

<class 'list'>


In [24]:
print(type(array_list))

<class 'numpy.ndarray'>


In [25]:
import numpy as np
list_ =['1','2','3','4','5']
array_list = np.array(object = list_, dtype =int)

for element in list_:
    print(type(element))
    
for element in array_list:
    print(type(element))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [26]:
import numpy as np

In [28]:
num_list =[[1,2,3],[4,5,6]]

In [29]:
num_array = np.array(object = num_list)

#QNO.4 ANS

In [31]:
num_array.shape

(2, 3)

In [32]:
num_array.size

6

#QNO.5 ANS

In [35]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#QNO.6 ANS

In [37]:
import numpy as np
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])